FROM node:20-bullseye-slim

WORKDIR /app

# Copy dependency manifests
COPY package*.json ./

# Install ALL dependencies
RUN npm install

# Copy the entire project
COPY . .

# Expose the Vite port
EXPOSE 3180

# Production command for the frontend
CMD if [ "$NODE_ENV" = "production" ]; then \
    npm run build && npm run preview -- --host 0.0.0.0 --port 3180; \
    else \
    npm run dev:frontend -- --host 0.0.0.0 --port 3180; \
    fi
